# Writer of the STABLE lsfdev entry point, shared by lsfdev.ps1 (every run)
# and the plugin's SessionStart hook (hooks/lsfdev-session-start.ps1) - so the
# shim exists before the first lsfdev call on a fresh install and is
# re-pointed right after a plugin update, not only after somebody happens to
# run the versioned script. Dot-source this file, then call
#
#   Sync-StableShim -ScriptDir <directory of the real lsfdev.ps1>
#
# It returns the shim path (%LOCALAPPDATA%\lsfusion-dev\lsfdev.ps1) - or $null
# when no shim can be written - and sets $script:StableShimWritten to $true
# when this call (re)wrote the file. Never throws, never prints.
#
# Why a shim: when installed as a plugin, the real script's path carries the
# PLUGIN VERSION (...\plugins\cache\<marketplace>\lsfusion-ai-skills\<version>\
# skills\lsfusion-dev\scripts\lsfdev.ps1), so every plugin update kills any
# remembered absolute path - and any permission allow rule pinned to it. The
# shim is a tiny forwarder at a VERSION-INDEPENDENT path that re-resolves the
# newest installed skill copy at call time and forwards all arguments (and
# the exit code) to it. That path is the one to remember, document, and put
# in session memories and permission rules.

function Get-StableShimPath {
    if (-not $env:LOCALAPPDATA) { return $null }
    return (Join-Path (Join-Path $env:LOCALAPPDATA "lsfusion-dev") "lsfdev.ps1")
}

function Sync-StableShim([string]$ScriptDir) {
    $script:StableShimWritten = $false
    try {
        if (-not $env:LOCALAPPDATA) { return $null }
        if (-not $ScriptDir) { $ScriptDir = $PSScriptRoot }
        $shimDir = Join-Path $env:LOCALAPPDATA "lsfusion-dev"
        # Degenerate install guard: if the real script already runs from the
        # shim location, rewriting it would overwrite the running file with
        # forwarder text and orphan the next call.
        if ("$ScriptDir".TrimEnd('\') -ieq $shimDir.TrimEnd('\')) { return (Join-Path $shimDir "lsfdev.ps1") }
        $self = Join-Path $ScriptDir "lsfdev.ps1"
        # The cache root the real script is installed under (...\<root>\
        # <marketplace>\lsfusion-ai-skills\<version>\skills\lsfusion-dev\
        # scripts). Embedded into the shim as an extra search root, so
        # nonstandard cache locations (relocated config dirs, custom cache
        # env vars) keep working: a plugin update lands in the same root the
        # current copy runs from. Empty when the layout is not a versioned
        # plugin cache (e.g. a repo checkout) - the shim then relies on the
        # other roots and the literal fallback path.
        $cacheRoot = ""
        try {
            # scripts -> lsfusion-dev -> skills -> <version>; then the root is
            # THREE more levels up (<version> -> lsfusion-ai-skills ->
            # <marketplace> -> root), matching the shim's
            # <root>\*\lsfusion-ai-skills\*\skills\... glob shape. Both the
            # version-looking leaf and the plugin-dir name are asserted, so a
            # repo checkout (or any other layout) embeds nothing.
            $verDir = Split-Path (Split-Path (Split-Path $ScriptDir -Parent) -Parent) -Parent
            if ($verDir -and ((Split-Path $verDir -Leaf) -match '^\d+(\.\d+)*([.-].+)?$')) {
                $pluginDir = Split-Path $verDir -Parent
                if ($pluginDir -and ((Split-Path $pluginDir -Leaf) -ieq 'lsfusion-ai-skills')) {
                    $cacheRoot = Split-Path (Split-Path $pluginDir -Parent) -Parent
                }
            }
        } catch { }
        $shimText = @'
# Auto-generated by the lsfusion-dev skill - STABLE entry point for lsfdev.ps1.
# Installed by the plugin's session-start hook and refreshed by every lsfdev
# run. The real script lives under the Claude plugin cache, whose path
# contains the plugin VERSION and changes on every plugin update; THIS path
# never changes. The shim re-resolves the newest installed copy on every call
# and forwards all arguments and the exit code. Remember this path - and put
# only this path in permission allow rules - never the versioned one.
# Search roots: CLAUDE_CONFIG_DIR\plugins\cache (relocated config dir), the
# cache root the generating copy was installed under, and the default
# USERPROFILE\.claude\plugins\cache.
$roots = @()
if ($env:CLAUDE_CONFIG_DIR) { $roots += (Join-Path $env:CLAUDE_CONFIG_DIR 'plugins\cache') }
$roots += '__CACHEROOT__'
if ($env:USERPROFILE) { $roots += (Join-Path $env:USERPROFILE '.claude\plugins\cache') }
$cands = @()
foreach ($r in @($roots | Where-Object { $_ } | Select-Object -Unique)) {
    $cands += @(Get-ChildItem (Join-Path $r '*\lsfusion-ai-skills\*\skills\lsfusion-dev\scripts\lsfdev.ps1') -ErrorAction SilentlyContinue)
}
$cands = @($cands | Sort-Object -Property FullName -Unique)
$real = $null
# Sort key of a plugin version dir name, compared ORDINALLY, so that key
# order is SemVer precedence: numeric parts are length-prefixed digit strings
# (numeric order at any width, no integer conversion), joined by spaces (a
# space sorts below every identifier character); then ' 1' for a release or
# ' 0 <prerelease identifiers>' - a numeric identifier is '0' + its
# length-prefixed digits, any other identifier '1' + the text, so numerics
# rank below alphanumerics, 'alpha' < 'alpha.1' < 'alpha-1', and
# 0.1.45-beta.1 sorts below 0.1.45 and above 0.1.44 ([version] cannot parse
# prereleases and would rank them last). A name that is not a complete
# version (a commit hash, a stray folder) yields '' and never wins over a
# version.
function Get-VerKey([string]$n) {
    if (-not ($n -match '^(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:-([0-9A-Za-z.-]+))?(?:\+[0-9A-Za-z.-]+)?$')) { return '' }
    $m = $Matches
    $num = { param([string]$s) $s = $s.TrimStart('0'); if ($s -eq '') { $s = '0' }; ('{0:D3}' -f $s.Length) + $s }
    $k = (@(1, 2, 3 | ForEach-Object { if ($m.ContainsKey($_) -and "$($m[$_])" -ne '') { & $num "$($m[$_])" } else { & $num '0' } })) -join ' '
    if ($m.ContainsKey(4) -and "$($m[4])" -ne '') {
        $k += ' 0 ' + ((@("$($m[4])" -split '\.') | ForEach-Object { if ($_ -match '^\d+$') { '0' + (& $num $_) } else { '1' + $_ } }) -join ' ')
    } else { $k += ' 1' }
    return $k
}
if ($cands.Count) {
    # The newest installed version wins - a plugin update lands in a new
    # version dir and must be picked up at once; the .in_use marker only
    # breaks a tie between equal versions under different roots.
    $bestKey = $null
    $bestUse = 0
    foreach ($c in $cands) {
        $k = Get-VerKey $c.Directory.Parent.Parent.Parent.Name
        $u = [int][bool](Test-Path (Join-Path $c.Directory.Parent.Parent.Parent.FullName '.in_use'))
        $cmp = if ($null -eq $bestKey) { 1 } else { [string]::CompareOrdinal($k, $bestKey) }
        if ($cmp -gt 0 -or ($cmp -eq 0 -and $u -gt $bestUse)) { $real = $c.FullName; $bestKey = $k; $bestUse = $u }
    }
}
if (-not $real -and (Test-Path '__FALLBACK__')) { $real = '__FALLBACK__' }
if (-not $real) {
    Write-Host "[FAIL] No installed lsfusion-dev skill found: the plugin cache glob matched nothing and the copy that generated this shim is gone. Reinstall the lsfusion-ai-skills plugin (or call its skills\lsfusion-dev\scripts\lsfdev.ps1 directly)." -ForegroundColor Red
    exit 1
}
# An in-process caller reads $LASTEXITCODE afterwards; without this reset a
# stale nonzero value from an unrelated earlier native command would leak
# through when the real script completes without running one.
$global:LASTEXITCODE = 0
& $real @args
exit $LASTEXITCODE
'@
        # Apostrophes in paths (C:\Users\O'Brien\...) must be doubled - the
        # placeholders sit inside single-quoted literals in the shim text.
        $shimText = $shimText.Replace('__FALLBACK__', $self.Replace("'", "''"))
        $shimText = $shimText.Replace('__CACHEROOT__', "$cacheRoot".Replace("'", "''"))
        $shimPath = Join-Path $shimDir "lsfdev.ps1"
        $current = ""
        if (Test-Path $shimPath) { try { $current = [IO.File]::ReadAllText($shimPath) } catch { } }
        if ($current -ne $shimText) {
            New-Item -ItemType Directory -Force -Path $shimDir | Out-Null
            # UTF-8 WITH BOM: Windows PowerShell 5.1 reads a BOM-less .ps1 in
            # the ANSI code page, which would mangle a non-ASCII fallback
            # path embedded above (ReadAllText strips the BOM, so the
            # comparison stays exact).
            [IO.File]::WriteAllText($shimPath, $shimText, (New-Object System.Text.UTF8Encoding($true)))
            $script:StableShimWritten = $true
        }
        return $shimPath
    } catch { return $null }
}
